import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Martian_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const martianMono = Martian_Mono({
  variable: "--font-martian-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "eve's website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>evelyn's site</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, #CB8AC0" />
      </head>

      <body
        className={`${martianMono.variable} ${martianMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
