import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {Martian_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const martianMono = Martian_Mono({
    variable: "--font-martian-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta name="theme-color" content="#CB8AC0"/>
        </head>
        <body
            className={`${martianMono.variable} ${martianMono.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
